name: Auto Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.event.ref }}
          base: main
          title: Automatic Pull Request
          labels: auto-pull-request
          body: "This is an automatic pull request."

  wait_for_approval:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Approval
        uses: wei/pull-request-wait-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
