name: CI/CD Dev to Test
on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        # Add your build and test commands here
        # Example: npm install && npm test
        
    - name: Push to Test Repository
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main  # Change this to the target branch in my-app-test
        directory: ./  # Directory containing the code you want to push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

