on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "eng21ct0007@dsu.edu.in"
        git config --global user.name "hrk-2109"
    
    - name: Push to Target Repo
      run: |
        git clone https://github.com/Techtidy/my-app-dev.git 
        cd https://github.com/Techtidy/my-app-test
        git checkout main  
        cp -r ../path/to/files/* . 
        git add .
        git commit -m "Automated push from source repository"
        git push
        cd ..

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
