name: Dev to Test

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push code to test
      run: |
        git remote add test-repo https://github.com/Techtidy/my-app-test.git
        git push test-repo main
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
