name: Push to test Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to Destination Repository
        run: |
          git config user.name "hrk-2109"
          git config user.email "eng21ct0007@dsu.edu.in"
          git clone https://github.com/Techtidy/my-app-dev.git
           cd my-app-test
           cp -R my-app-dev/* my-app-test/
          git add .
          git commit -m "Automated update from source repository"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
