name: Push to Test Repository

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Test Repository
        run: |
          git clone https://github.com/Techtidy/my-app-test.git
          cd my-app-test
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Configure Git
        run: |
          git config user.email "eng21ct0007@dsu.edu.in"
          git config user.name "Harika"
        working-directory: ./my-app-test

      - name: Push to Test Repository
        run: |
          cp -R .././* .
          git add .
          git commit -m "Auto push from dev repository"
          git push origin main
        working-directory: ./my-app-test
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
