name: trigger in other repository
on: 
  push:
      branches:
           -main
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: Techtidy/my-appp-test
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'
          
