name: Deploy to Test

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to test repository
        run: |
          git config --global user.name "hrk-2109"
          git config --global user.email "eng21ct0007@dsu.edu.in"
          git clone --mirror https://github.com/Techtidy/my-app-dev.git
          cd my-app-dev.git
          git push --mirror https://github.com/Techtidy/my-app-test.git
        env:
          TOKEN: ${{ secrets.token }}
