name: Pull Request Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge a pull request
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          allowed-usernames-regex: ^williamdes$
          filter-label: merge-it

      - name: Merge a pull request without any need for a label (automatic merge)
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          allowed-usernames-regex: ^williamdes$

      - name: Merge a pull request with message and body (optional)
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          merge-method: merge
          allowed-usernames-regex: ^williamdes$
          filter-label: merge-it
          merge-title: "Merge #${{ github.event.pull_request.number }}"
          merge-message: "Merge #${{ github.event.pull_request.number }}"

      - name: Merge a pull request using fast-forward
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          merge-method: fast-forward
          allowed-usernames-regex: ^williamdes$
          filter-label: merge-it

  review:
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Approve pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            });
            console.log(response.data);
