name: Zap API Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Zap API Scan
        run: npm run zap-scan

- name: Install Zap CLI
  run: |
    wget https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
    tar -zxvf ZAP_2.10.0_Linux.tar.gz
    export PATH=$PATH:$PWD/ZAP_2.10.0

// Example zap-scan script in package.json
"scripts": {
  "zap-scan": "zap-cli --url http://example.com --quick-scan --output /path/to/report.html"
}
